# Generated by Django 5.2.12 on 2026-03-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_user_id_bb1b83_idx',
            old_name='user_sessions_user_active_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_jti_d905be_idx',
            old_name='user_sessions_jti_idx',
        ),
        migrations.RenameIndex(
            model_name='usersession',
            new_name='user_sessio_last_ac_7cb421_idx',
            old_name='user_sessions_last_activity_idx',
        ),
    ]
