# Generated by Django 5.2.12 on 2026-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beat_auth', '0004_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(blank=True, choices=[('developer', 'Desarrollador'), ('client', 'Cliente'), ('admin', 'Administrador')], default='client', max_length=20, verbose_name='Tipo de perfil'),
        ),
    ]
