# Generated by Django 5.2.12 on 2026-03-18 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('version', models.PositiveIntegerField(default=1, help_text='Record version for optimistic locking', verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about changes', verbose_name='Notes')),
                ('name', models.CharField(help_text='Country name in Spanish (base language)', max_length=100, unique=True, verbose_name='Country Name')),
                ('code_iso2', models.CharField(help_text='ISO 3166-1 alpha-2 country code (e.g., MX, US, ES)', max_length=2, unique=True, verbose_name='ISO 2-letter Code')),
                ('code_iso3', models.CharField(help_text='ISO 3166-1 alpha-3 country code (e.g., MEX, USA, ESP)', max_length=3, unique=True, verbose_name='ISO 3-letter Code')),
                ('numeric_code', models.CharField(blank=True, help_text='ISO 3166-1 numeric country code', max_length=3, unique=True, verbose_name='Numeric Code')),
                ('name_pt', models.CharField(blank=True, help_text='Country name in Portuguese', max_length=100, verbose_name='Name in Portuguese')),
                ('name_en', models.CharField(blank=True, help_text='Country name in English', max_length=100, verbose_name='Name in English')),
                ('name_fr', models.CharField(blank=True, help_text='Country name in French', max_length=100, verbose_name='Name in French')),
                ('name_it', models.CharField(blank=True, help_text='Country name in Italian', max_length=100, verbose_name='Name in Italian')),
                ('phone_code', models.CharField(blank=True, help_text='International dialing code (e.g., +52, +1, +34)', max_length=5, verbose_name='Phone Country Code')),
                ('currency_code', models.CharField(blank=True, help_text='ISO 4217 currency code (e.g., MXN, USD, EUR)', max_length=3, verbose_name='Currency Code')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country is available for selection', verbose_name='Is Active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Order for displaying countries (0 = first)', verbose_name='Sort Order')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['code_iso2', 'is_active'], name='core_countr_code_is_9a1a35_idx'), models.Index(fields=['sort_order', 'is_active'], name='core_countr_sort_or_3639de_idx'), models.Index(fields=['name'], name='core_countr_name_5737bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('version', models.PositiveIntegerField(default=1, help_text='Record version for optimistic locking', verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about changes', verbose_name='Notes')),
                ('name', models.CharField(help_text='Name or description of this location', max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Optional description of the location', verbose_name='Description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location is active and available', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'core_location',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='core_locati_is_acti_d10f4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Deleted at')),
                ('version', models.PositiveIntegerField(default=1, help_text='Record version for optimistic locking', verbose_name='Version')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about changes', verbose_name='Notes')),
                ('title', models.CharField(help_text='Notification title', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Notification message content', verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('reminder', 'Reminder'), ('message', 'Message')], default='info', help_text='Type of notification', max_length=20, verbose_name='Notification Type')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read', verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True, verbose_name='Read At')),
                ('url', models.CharField(blank=True, help_text='Optional URL to redirect when clicking the notification', max_length=500, verbose_name='URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as JSON', verbose_name='Metadata')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted by')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('user', models.ForeignKey(help_text='User who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx'), models.Index(fields=['user', 'is_read'], name='core_notifi_user_id_cb8f07_idx'), models.Index(fields=['is_read', '-created_at'], name='core_notifi_is_read_57d3f5_idx')],
            },
        ),
    ]
